### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method

### ISSUE THREAD

**Issue by mattdell** [indicee/html-to-react#2]
I'm getting this error on some HTML I've rendered. Does this library have support for keys?

**Comment by hollandmatt** [comment]
@mattdell Could you post the HTML you're having the issue with? Are you actually experiencing "squashing" of the DOM (where React strips out what it thinks are duplicates) or just the console warning?

**Comment by mattdell** [comment]
Thanks for the quick response! This is the HTML causing the problem...

`<p>Send an <a href=\'#\'>email</a>, give us a call on <a href=\'#\'>00000 000000</a> or see our <a href=\'#\'>FAQs</a>.</p>`

Though I have a helper util that wraps everything in a div since the library requires a single parent so that resolves to

`<div><p>Send an <a href=\'#\'>email</a>, give us a call on <a href=\'#\'>00000 000000</a> or see our <a href=\'#\'>FAQs</a>.</p></div>`

It's simply the console warning I want to avoid.

**Comment by hollandmatt** [comment]
We do attempt to add a key: https://github.com/indicee/html-to-react/blob/master/lib/process-node-definitions.js#L32 but maybe this isn't working quite right?

**Comment by mattdell** [comment]
Hmm, I don't see where a key is being added. We basically need to have 

`<p>Send an <a href=\'#\' key='0'>email</a>, give us a call on <a href=\'#\' key='1'>00000 000000</a> or see our <a href=\'#\' key='3'>FAQs</a>.</p>`

Or something to that effect. Currently looking through the code to imagine how this could be done.

**Comment by hollandmatt** [comment]
The `elementProps` being created at line 33 (which includes a `key`), is then passed to the `React.createElement` call at line 51. That /should/ be doing what we need.

**Comment by mattdell** [comment]
Ah, interesting... I don't seem to have that line!

**Comment by hollandmatt** [comment]
Ahh, the package in NPM at https://www.npmjs.com/package/html-to-react is from this Git repo: https://github.com/mikenikles/html-to-react but I see you found that already!

**Comment by mattdell** [comment]
Yeah, that was a bit confusing. Why is there two? And is this one available as an npm package?
